wsplugin.push.enabled=true
wsplugin.push.rules.platform=platform
wsplugin.push.rules.platform.endpoint=http://backend-service-party-a:8080/api/edelivery/messages
wsplugin.push.rules.platform.retry=1;1;SEND_ONCE
wsplugin.push.rules.platform.type=SUBMIT_MESSAGE
