# https://docs.edelivery.tech.ec.europa.eu/domismp/prod/5.1/#smp_propsref

smp.jdbc.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
smp.jdbc.driver=com.mysql.jdbc.Driver
smp.jdbc.url=jdbc:mysql://smp-db-1:3306/harmony_smp
smp.jdbc.user=harmony_smp
smp.jdbc.password=local-pwd-123
spring.jpa.generate-ddl=false

smp.passwordPolicy.validationRegex="^.+"
smp.passwordPolicy.validationMessage=See configuration for password regex
smp.passwordPolicy.validDays=365

# Specifies the time, in seconds, between client requests before the SMP will invalidate session for ADMIN users (System).
# 24 hours
smp.ui.session.idle_timeout.admin=86400
# Specifies the time, in seconds, between client requests before the SMP will invalidate session for users (Service group, SMP Admin).
# 24 hours
smp.ui.session.idle_timeout.user=86400

bdmsl.integration.enabled=true
bdmsl.integration.dns.zone=some-sml-zone.test.edelivery.internal
bdmsl.integration.logical.address=http://smp-1:8080/harmonysmp
bdmsl.integration.physical.address=172.99.0.6
bdmsl.integration.url=http://sml:8080/edelivery-sml/

# *********************************
# Certificate configuration for SML integration
# https://docs.edelivery.tech.ec.europa.eu/domismp/prod/5.1/#smp_propsref
# https://github.com/nordic-institute/harmony-common/blob/main/doc/dynamic_discovery_configuration_guide.md#32-keys-and-certificates
# *********************************
smp.security.folder=/certs
# default path if not set: /usr/local/tomcat/smp/encryptionPrivateKey.private
encryption.key.filename=encryptionPrivateKey.private

# Client keystore (SMP client certificate for authentication with SML)
smp.keystore.filename=smp-client.p12
# ./sml-password-hash.sh store-pwd-123
smp.keystore.password=qZt56gXc2/KhkbnTUgJyTbjGDGqgVa3jiJ96/u0=
smp.keystore.type=PKCS12

# Truststore (trusts SML server certificates)
smp.truststore.filename=smp-truststore.p12
# ./sml-password-hash.sh store-pwd-123
smp.truststore.password=qZt56gXc2/KhkbnTUgJyTbjGDGqgVa3jiJ96/u0=
smp.truststore.type=PKCS12


